# Generated by Django 4.1.3 on 2023-03-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='usermessage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='userphone',
            new_name='phone',
        ),
    ]
