# Generated by Django 4.1.3 on 2023-03-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0003_rename_usermessage_contact_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='usermessage',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='userphone',
        ),
    ]
