# Generated by Django 4.1.3 on 2023-03-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0006_rename_service_services_servicename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='service',
        ),
    ]
