# Generated by Django 4.1.3 on 2023-03-17 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0008_gallery_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_tb',
            name='caption',
            field=models.CharField(default=datetime.datetime(2023, 3, 17, 10, 15, 24, 236822, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
