# Generated by Django 4.1.3 on 2023-03-18 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0009_gallery_tb_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='getprice_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('useremail', models.CharField(max_length=255)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveapp.service')),
            ],
        ),
    ]
