# Generated by Django 4.1.3 on 2023-03-18 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0010_getprice_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='getprice_tb',
            name='userphone',
            field=models.CharField(default=datetime.datetime(2023, 3, 18, 6, 28, 22, 837231, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
