# Generated by Django 4.1.3 on 2023-03-18 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0011_getprice_tb_userphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='getprice_tb',
            name='details',
            field=models.CharField(default=datetime.datetime(2023, 3, 18, 6, 47, 36, 171099, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
