# Generated by Django 4.1.3 on 2023-03-18 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0012_getprice_tb_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='useremail',
            field=models.CharField(default=datetime.datetime(2023, 3, 18, 10, 39, 29, 212835, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
